// require("dotenv").config();
// const connectDB = require("./config/db");

// const sampleProducts = [
//   {
//     name: "iPhone 15 Pro",
//     brand: "Apple",
//     type: "mobile",
//     price: 145000,
//     images: ["https://i.ibb.co.com/jZwD6v1Y/banner-01.jpg"],
//     specs: { ram: "8GB", storage: "256GB", display: "6.1 inch OLED" },
//     shortDescription: "Apple-এর সর্বশেষ প্রিমিয়াম মডেল",
//     fullDescription: "বিস্তারিত বর্ণনা এখানে লিখবেন",
//     releaseYear: 2023,
//     createdAt: new Date(),
//   },
//   {
//     name: "Galaxy S24 Ultra",
//     brand: "Samsung",
//     type: "mobile",
//     price: 132000,
//     images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
//     specs: { ram: "12GB", storage: "512GB", display: "6.8 inch AMOLED" },
//     shortDescription: "Samsung-এর ফ্ল্যাগশিপ মডেল",
//     fullDescription: "বিস্তারিত বর্ণনা এখানে লিখবেন",
//     releaseYear: 2024,
//     createdAt: new Date(),
//   },
//   {
//     name: "MacBook Pro M3",
//     brand: "Apple",
//     type: "laptop",
//     price: 210000,
//     images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
//     specs: {
//       ram: "16GB",
//       storage: "512GB SSD",
//       display: "14.2 inch Liquid Retina XDR",
//     },
//     shortDescription: "প্রফেশনাল কাজের জন্য শক্তিশালী অ্যাপল ল্যাপটপ",
//     fullDescription: "বিস্তারিত বর্ণনা এখানে লিখবেন",
//     releaseYear: 2023,
//     createdAt: new Date(),
//   },
//   {
//     name: "Apple Watch Ultra 2",
//     brand: "Apple",
//     type: "watch",
//     price: 89000,
//     images: ["https://i.ibb.co.com/jZwD6v1Y/banner-01.jpg"],
//     specs: {
//       battery: "36 Hours",
//       display: "49mm Always-On Retina",
//       connectivity: "GPS + Cellular",
//     },
//     shortDescription: "টাফ, প্রিসিশন-ইঞ্জিনিয়ার্ড স্মার্টওয়াচ",
//     fullDescription: "বিস্তারিত বর্ণনা এখানে লিখবেন",
//     releaseYear: 2023,
//     createdAt: new Date(),
//   },
//   {
//     name: "iPad Pro 11",
//     brand: "Apple",
//     type: "tablet",
//     price: 115000,
//     images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
//     specs: {
//       ram: "8GB",
//       storage: "128GB",
//       display: "11 inch Ultra Retina XDR",
//     },
//     shortDescription: "সৃজনশীল কাজ এবং পোর্টেবিলিটির জন্য সেরা ট্যাব",
//     fullDescription: "বিস্তারিত বর্ণনা এখানে লিখবেন",
//     releaseYear: 2024,
//     createdAt: new Date(),
//   },
// ];

// const seed = async () => {
//   const db = await connectDB();
//   await db.collection("products").insertMany(sampleProducts);
//   console.log(`${sampleProducts.length}টা প্রোডাক্ট যোগ হয়েছে`);
//   process.exit(0);
// };

// seed().catch((err) => {
//   console.error(err);
//   process.exit(1);
// });

// 2
// require("dotenv").config();
// const connectDB = require("./config/db");

// const sampleProducts = [
//   {
//     name: "iPhone 15 Pro",
//     brand: "Apple",
//     type: "mobile",
//     price: 145000,
//     images: ["https://i.ibb.co.com/jZwD6v1Y/banner-01.jpg"],
//     specs: { ram: "8GB", storage: "256GB", display: "6.1 inch OLED" },
//     shortDescription: "Apple's latest premium flagship model",
//     fullDescription: "Detailed description will be added here",
//     releaseYear: 2023,
//     createdAt: new Date(),
//   },
//   {
//     name: "Galaxy S24 Ultra",
//     brand: "Samsung",
//     type: "mobile",
//     price: 132000,
//     images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
//     specs: { ram: "12GB", storage: "512GB", display: "6.8 inch AMOLED" },
//     shortDescription: "Samsung's flagship mobile device",
//     fullDescription: "Detailed description will be added here",
//     releaseYear: 2024,
//     createdAt: new Date(),
//   },
//   {
//     name: "MacBook Pro M3",
//     brand: "Apple",
//     type: "laptop",
//     price: 210000,
//     images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
//     specs: {
//       ram: "16GB",
//       storage: "512GB SSD",
//       display: "14.2 inch Liquid Retina XDR",
//     },
//     shortDescription: "Powerful Apple laptop built for professional work",
//     fullDescription: "Detailed description will be added here",
//     releaseYear: 2023,
//     createdAt: new Date(),
//   },
//   {
//     name: "Apple Watch Ultra 2",
//     brand: "Apple",
//     type: "watch",
//     price: 89000,
//     images: ["https://i.ibb.co.com/jZwD6v1Y/banner-01.jpg"],
//     specs: {
//       battery: "36 Hours",
//       display: "49mm Always-On Retina",
//       connectivity: "GPS + Cellular",
//     },
//     shortDescription: "Tough, precision-engineered smartwatch",
//     fullDescription: "Detailed description will be added here",
//     releaseYear: 2023,
//     createdAt: new Date(),
//   },
//   {
//     name: "iPad Pro 11",
//     brand: "Apple",
//     type: "tablet",
//     price: 115000,
//     images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
//     specs: {
//       ram: "8GB",
//       storage: "128GB",
//       display: "11 inch Ultra Retina XDR",
//     },
//     shortDescription: "The best tablet for creative work and portability",
//     fullDescription: "Detailed description will be added here",
//     releaseYear: 2024,
//     createdAt: new Date(),
//   },
// ];

// const seed = async () => {
//   const db = await connectDB();
//   await db.collection("products").insertMany(sampleProducts);
//   console.log(`${sampleProducts.length} products inserted successfully`);
//   process.exit(0);
// };

// seed().catch((err) => {
//   console.error(err);
//   process.exit(1);
// });

// 3

require("dotenv").config();
const connectDB = require("./config/db");

const sampleProducts = [
  // --- 1. Apple ---
  {
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    type: "mobile",
    price: 165000,
    images: ["https://i.ibb.co.com/bgvR4xKj/i-Phone-15-Pro-Max.webp"],
    specs: {
      ram: "8GB",
      storage: "256GB",
      display: "6.7 inch Super Retina XDR",
    },
    shortDescription: "Premium flagship iPhone with Titanium design",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "iPhone 16 Pro",
    brand: "Apple",
    type: "mobile",
    price: 175000,
    images: ["https://i.ibb.co.com/FpM64Ws/i-Phone-16-Pro.webp"],
    specs: {
      ram: "8GB",
      storage: "256GB",
      display: "6.3 inch Super Retina XDR",
    },
    shortDescription: "Latest flagship with Apple Intelligence",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "iPad Pro 11 M4",
    brand: "Apple",
    type: "tablet",
    price: 135000,
    images: ["https://i.ibb.co.com/rR9qLsWG/i-Pad-Pro-11-M4.jpg"],
    specs: {
      ram: "8GB",
      storage: "256GB",
      display: "11 inch Ultra Retina XDR",
    },
    shortDescription: "Ultra-thin powerful tablet with M4 chip",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "iPad Air 11 M2",
    brand: "Apple",
    type: "tablet",
    price: 85000,
    images: ["https://i.ibb.co.com/fVnRVKPw/i-Pad-Air-11-M2.webp"],
    specs: { ram: "8GB", storage: "128GB", display: "11 inch Liquid Retina" },
    shortDescription: "Versatile performance tablet powered by M2",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Apple Watch Ultra 2",
    brand: "Apple",
    type: "watch",
    price: 89000,
    images: ["https://i.ibb.co.com/nN4jWyr9/Apple-Watch-Ultra-2.jpg"],
    specs: {
      battery: "36 Hours",
      display: "49mm Always-On Retina",
      connectivity: "GPS + Cellular",
    },
    shortDescription: "Rugged and capable smartwatch for athletes",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Apple Watch Series 10",
    brand: "Apple",
    type: "watch",
    price: 55000,
    images: ["https://i.ibb.co.com/ym5Zr92N/Apple-Watch-Series-10.jpg"],
    specs: {
      battery: "18 Hours",
      display: "46mm OLED Display",
      connectivity: "GPS",
    },
    shortDescription: "Sleek smartwatch with wide-angle OLED display",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "MacBook Pro 14 M3",
    brand: "Apple",
    type: "laptop",
    price: 210000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      display: "14.2 inch Liquid Retina XDR",
    },
    shortDescription: "Pro laptop for intensive creative workflows",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "MacBook Air 13 M3",
    brand: "Apple",
    type: "laptop",
    price: 145000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: {
      ram: "8GB",
      storage: "256GB SSD",
      display: "13.6 inch Liquid Retina",
    },
    shortDescription: "Ultra-portable performance laptop",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },

  // --- 2. Samsung ---
  {
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    type: "mobile",
    price: 135000,
    images: ["https://i.ibb.co.com/kgxC6Tb1/Galaxy-S24-Ultra.webp"],
    specs: {
      ram: "12GB",
      storage: "512GB",
      display: "6.8 inch Dynamic AMOLED 2X",
    },
    shortDescription: "Samsung flagship with AI features and S-Pen",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Galaxy A55 5G",
    brand: "Samsung",
    type: "mobile",
    price: 48000,
    images: ["https://i.ibb.co.com/5W3vgDWS/Galaxy-A55-5-G.webp"],
    specs: { ram: "8GB", storage: "128GB", display: "6.6 inch Super AMOLED" },
    shortDescription: "Mid-range champion with premium glass back",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Galaxy Tab S9 Ultra",
    brand: "Samsung",
    type: "tablet",
    price: 120000,
    images: ["https://i.ibb.co.com/YT2cv6TZ/Galaxy-Tab-S9-Ultra.webp"],
    specs: { ram: "12GB", storage: "256GB", display: "14.6 inch AMOLED" },
    shortDescription: "Massive productivity tablet with S-Pen",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Galaxy Tab A9+",
    brand: "Samsung",
    type: "tablet",
    price: 28000,
    images: ["https://i.ibb.co.com/rGVJYTcd/Galaxy-Tab-A9.jpg"],
    specs: { ram: "4GB", storage: "64GB", display: "11.0 inch LCD 90Hz" },
    shortDescription: "Affordable family tablet for entertainment",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Galaxy Watch Ultra",
    brand: "Samsung",
    type: "watch",
    price: 68000,
    images: ["https://i.ibb.co.com/PsVYxK4t/Galaxy-Watch-Ultra.webp"],
    specs: {
      battery: "60 Hours",
      display: "47mm Super AMOLED",
      connectivity: "LTE",
    },
    shortDescription: "Durable smartwatch designed for extreme adventures",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Galaxy Watch 7",
    brand: "Samsung",
    type: "watch",
    price: 35000,
    images: ["https://i.ibb.co.com/1GCRwkyP/Galaxy-Watch-7.webp"],
    specs: {
      battery: "30 Hours",
      display: "44mm Super AMOLED",
      connectivity: "Bluetooth",
    },
    shortDescription: "Daily health tracker with advanced BioActive Sensor",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Galaxy Book4 Pro",
    brand: "Samsung",
    type: "laptop",
    price: 185000,
    images: ["https://i.ibb.co.com/mF9Zryp9/Galaxy-Book4-Pro.jpg"],
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      display: "16.0 inch Dynamic AMOLED 2X",
    },
    shortDescription: "Sleek and powerful laptop with AI integration",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Galaxy Book3 360",
    brand: "Samsung",
    type: "laptop",
    price: 125000,
    images: ["https://i.ibb.co.com/5XxX959r/Galaxy-Book3-360.webp"],
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      display: "15.6 inch FHD AMOLED Touch",
    },
    shortDescription: "2-in-1 convertible touchscreen laptop",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },

  // --- 3. Huawei ---
  {
    name: "Huawei Pura 70 Ultra",
    brand: "Huawei",
    type: "mobile",
    price: 140000,
    images: ["https://i.ibb.co.com/k6v8Xr7P/Huawei-Pura-70-Ultra.jpg"],
    specs: { ram: "16GB", storage: "512GB", display: "6.8 inch LTPO OLED" },
    shortDescription: "Flagship mobile with retractable camera lens",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Huawei Mate 60 Pro",
    brand: "Huawei",
    type: "mobile",
    price: 115000,
    images: ["https://i.ibb.co.com/YwT6KZT/Huawei-Mate-60-Pro.jpg"],
    specs: { ram: "12GB", storage: "512GB", display: "6.82 inch LTPO OLED" },
    shortDescription: "Advanced satellite connectivity smartphone",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Huawei MateBook X Pro",
    brand: "Huawei",
    type: "laptop",
    price: 215000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: {
      ram: "32GB",
      storage: "1TB SSD",
      display: "14.2 inch Flexible OLED",
    },
    shortDescription: "Ultra-lightweight premium laptop",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Huawei MateBook D 16",
    brand: "Huawei",
    type: "laptop",
    price: 78000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: { ram: "16GB", storage: "512GB SSD", display: "16.0 inch IPS LCD" },
    shortDescription: "Large display laptop for everyday work",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Huawei MatePad Pro 13.2",
    brand: "Huawei",
    type: "tablet",
    price: 105000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "13.2 inch Flexible OLED",
    },
    shortDescription: "Slim flagship tablet with NearLink stylus support",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Huawei MatePad 11.5 S",
    brand: "Huawei",
    type: "tablet",
    price: 45000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: {
      ram: "8GB",
      storage: "256GB",
      display: "11.5 inch PaperMatte Display",
    },
    shortDescription: "Paper-like display tablet ideal for reading and writing",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Huawei Watch GT 4",
    brand: "Huawei",
    type: "watch",
    price: 24000,
    images: ["https://i.ibb.co.com/jZwD6v1Y/banner-01.jpg"],
    specs: {
      battery: "14 Days",
      display: "1.43 inch AMOLED",
      connectivity: "Bluetooth",
    },
    shortDescription: "Stylish smartwatch with incredible battery life",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Huawei Watch Ultimate",
    brand: "Huawei",
    type: "watch",
    price: 85000,
    images: ["https://i.ibb.co.com/jZwD6v1Y/banner-01.jpg"],
    specs: {
      battery: "14 Days",
      display: "1.5 inch LTPO AMOLED",
      connectivity: "Bluetooth",
    },
    shortDescription: "Luxury smartwatch built with liquid metal alloy",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },

  // --- 4. Google Pixel ---
  {
    name: "Google Pixel 9 Pro",
    brand: "Google Pixel",
    type: "mobile",
    price: 125000,
    images: ["https://i.ibb.co.com/Y7XwYk8T/Google-Pixel-9-Pro.jpg"],
    specs: {
      ram: "16GB",
      storage: "128GB",
      display: "6.3 inch Super Actua OLED",
    },
    shortDescription: "Google flagship smartphone powered by Tensor G4",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Google Pixel 8a",
    brand: "Google Pixel",
    type: "mobile",
    price: 58000,
    images: ["https://i.ibb.co.com/0RCSHp08/Google-Pixel-8a.jpg"],
    specs: { ram: "8GB", storage: "128GB", display: "6.1 inch Actua OLED" },
    shortDescription: "Best budget camera smartphone with AI capabilities",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Google Pixel Tablet",
    brand: "Google Pixel",
    type: "tablet",
    price: 52000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "8GB", storage: "128GB", display: "10.95 inch LCD" },
    shortDescription: "Smart home integrated tablet with Charging Speaker Dock",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Google Pixel Tablet Standalone",
    brand: "Google Pixel",
    type: "tablet",
    price: 45000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "8GB", storage: "128GB", display: "10.95 inch LCD" },
    shortDescription: "Versatile entertainment tablet powered by Tensor G2",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Google Pixel Watch 3",
    brand: "Google Pixel",
    type: "watch",
    price: 42000,
    images: ["https://i.ibb.co.com/jZwD6v1Y/banner-01.jpg"],
    specs: {
      battery: "24 Hours",
      display: "45mm Actua AMOLED",
      connectivity: "Bluetooth",
    },
    shortDescription: "Smartwatch with deep Fitbit health integration",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Google Pixel Watch 2",
    brand: "Google Pixel",
    type: "watch",
    price: 32000,
    images: ["https://i.ibb.co.com/jZwD6v1Y/banner-01.jpg"],
    specs: { battery: "24 Hours", display: "41mm AMOLED", connectivity: "LTE" },
    shortDescription: "Lightweight fitness watch with heart rate tracking",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },

  // --- 5. Asus ---
  {
    name: "Asus ROG Phone 8 Pro",
    brand: "Asus",
    type: "mobile",
    price: 130000,
    images: ["https://i.ibb.co.com/bjPw1sCj/Asus-ROG-Phone-8-Pro.jpg"],
    specs: { ram: "16GB", storage: "512GB", display: "6.78 inch AMOLED 165Hz" },
    shortDescription: "Ultimate gaming phone with AniMe Vision display",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Asus Zenfone 11 Ultra",
    brand: "Asus",
    type: "mobile",
    price: 98000,
    images: ["https://i.ibb.co.com/MyvmzQn8/Asus-Zenfone-11-Ultra.webp"],
    specs: { ram: "12GB", storage: "256GB", display: "6.78 inch LTPO AMOLED" },
    shortDescription:
      "Flagship performance phone with gimbal camera stabilization",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Asus ROG Zephyrus G16",
    brand: "Asus",
    type: "laptop",
    price: 245000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: {
      ram: "32GB",
      storage: "1TB SSD",
      display: "16.0 inch ROG Nebula OLED 240Hz",
    },
    shortDescription: "Ultra-thin gaming laptop with RTX 4070 GPU",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Asus Zenbook 14 OLED",
    brand: "Asus",
    type: "laptop",
    price: 118000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: { ram: "16GB", storage: "512GB SSD", display: "14.0 inch 3K OLED" },
    shortDescription:
      "Premium ultraportable laptop powered by Intel Core Ultra",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },

  // --- 6. Xiaomi ---
  {
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    type: "mobile",
    price: 140000,
    images: ["https://i.ibb.co.com/xK8JY14K/Xiaomi-14-Ultra.webp"],
    specs: { ram: "16GB", storage: "512GB", display: "6.73 inch LTPO AMOLED" },
    shortDescription: "Ultimate photography phone co-engineered with Leica",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Redmi Note 13 Pro+ 5G",
    brand: "Xiaomi",
    type: "mobile",
    price: 42000,
    images: ["https://i.ibb.co.com/HTXg7fVh/Redmi-Note-13-Pro-5-G.webp"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.67 inch Curved AMOLED",
    },
    shortDescription:
      "Feature-packed mid-ranger with 200MP camera and IP68 rating",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },

  // --- 7. Vivo ---
  {
    name: "Vivo X100 Pro",
    brand: "Vivo",
    type: "mobile",
    price: 110000,
    images: ["https://i.ibb.co.com/1VXHKbB/Vivo-X100-Pro.webp"],
    specs: { ram: "16GB", storage: "512GB", display: "6.78 inch LTPO AMOLED" },
    shortDescription: "Pro camera smartphone with ZEISS optics",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Vivo V30 Pro",
    brand: "Vivo",
    type: "mobile",
    price: 52000,
    images: ["https://i.ibb.co.com/23WXyRg3/Vivo-V30-Pro.jpg"],
    specs: { ram: "12GB", storage: "512GB", display: "6.78 inch AMOLED 120Hz" },
    shortDescription: "Sleek portrait phone with Studio Quality Aura Light",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Vivo Pad 3 Pro",
    brand: "Vivo",
    type: "tablet",
    price: 65000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "13.1 inch 3.1K 144Hz LCD",
    },
    shortDescription: "High-performance tablet with Dimensity 9300 processor",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Vivo Pad Air",
    brand: "Vivo",
    type: "tablet",
    price: 32000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "8GB", storage: "128GB", display: "11.5 inch 144Hz LCD" },
    shortDescription:
      "Lightweight multimedia tablet for daily work and entertainment",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },

  // --- 8. Oppo ---
  {
    name: "Oppo Find X7 Ultra",
    brand: "Oppo",
    type: "mobile",
    price: 125000,
    images: ["https://i.ibb.co.com/zT5ZJvzy/Oppo-Find-X7-Ultra.jpg"],
    specs: { ram: "16GB", storage: "512GB", display: "6.82 inch LTPO AMOLED" },
    shortDescription: "World's first dual-periscope camera flagship",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Oppo Reno 12 Pro 5G",
    brand: "Oppo",
    type: "mobile",
    price: 55000,
    images: ["https://i.ibb.co.com/ymDSk61j/Oppo-Reno-12-Pro-5-G.jpg"],
    specs: { ram: "12GB", storage: "512GB", display: "6.7 inch AMOLED 120Hz" },
    shortDescription: "AI portrait camera phone with futuristic design",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Oppo Pad 2",
    brand: "Oppo",
    type: "tablet",
    price: 58000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: {
      ram: "8GB",
      storage: "256GB",
      display: "11.61 inch ReadFit Display",
    },
    shortDescription:
      "Unique 7:5 ratio screen tablet for enhanced reading productivity",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Oppo Pad Air 2",
    brand: "Oppo",
    type: "tablet",
    price: 26000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "6GB", storage: "128GB", display: "11.4 inch 2.4K 90Hz LCD" },
    shortDescription: "Eye-care focused budget tablet for students",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },

  // --- 9. Infinix ---
  {
    name: "Infinix GT 20 Pro",
    brand: "Infinix",
    type: "mobile",
    price: 35000,
    images: ["https://i.ibb.co.com/KpsZk7QN/Infinix-GT-20-Pro.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.78 inch FHD+ AMOLED 144Hz",
    },
    shortDescription: "Affordable gaming mobile with Mecha design",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Infinix Note 40 Pro+ 5G",
    brand: "Infinix",
    type: "mobile",
    price: 31000,
    images: ["https://i.ibb.co.com/0R8Gyhqm/Infinix-Note-40-Pro-5-G.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.78 inch 3D Curved AMOLED",
    },
    shortDescription: "Budget phone with 100W All-Round FastCharge",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Infinix INBook Y3 MAX",
    brand: "Infinix",
    type: "laptop",
    price: 48000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      display: "16.0 inch FHD Display",
    },
    shortDescription:
      "Large-screen budget laptop for students and professionals",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Infinix Zero Book Ultra",
    brand: "Infinix",
    type: "laptop",
    price: 88000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: { ram: "32GB", storage: "1TB SSD", display: "15.6 inch IPS LCD" },
    shortDescription:
      "High-performance creator laptop with Intel Core i9 processor",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },

  // --- 10. Motorola ---
  {
    name: "Motorola Razr 50 Ultra",
    brand: "Motorola",
    type: "mobile",
    price: 108000,
    images: ["https://i.ibb.co.com/6R8w82nm/Motorola-Razr-50-Ultra.jpg"],
    specs: {
      ram: "12GB",
      storage: "512GB",
      display: "6.9 inch Foldable pOLED 165Hz",
    },
    shortDescription: "Stylish flip smartphone with huge cover display",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Motorola Edge 50 Pro",
    brand: "Motorola",
    type: "mobile",
    price: 45000,
    images: ["https://i.ibb.co.com/3YcYff2X/Motorola-Edge-50-Pro.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.7 inch 1.5K pOLED 144Hz",
    },
    shortDescription: "Pantone-validated camera and display smartphone",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Moto Tab G70 2K",
    brand: "Motorola",
    type: "tablet",
    price: 25000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "4GB", storage: "64GB", display: "11.0 inch 2K IPS LCD" },
    shortDescription: "Entertainment tablet with Quad Speakers and Dolby Atmos",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2022,
    createdAt: new Date(),
  },
  {
    name: "Moto Tab G62",
    brand: "Motorola",
    type: "tablet",
    price: 19500,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "4GB", storage: "64GB", display: "10.61 inch 2K Display" },
    shortDescription: "Affordable Android tablet for learning and streaming",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2022,
    createdAt: new Date(),
  },

  // --- 11. Nothing ---
  {
    name: "Nothing Phone (2)",
    brand: "Nothing",
    type: "mobile",
    price: 65000,
    images: ["https://i.ibb.co.com/RTrWfhWB/Nothing-Phone-2.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.7 inch LTPO OLED 120Hz",
    },
    shortDescription: "Transparent smartphone with iconic Glyph Interface",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Nothing Phone (2a) Plus",
    brand: "Nothing",
    type: "mobile",
    price: 42000,
    images: ["https://i.ibb.co.com/bMySgh0W/Nothing-Phone-2a-Plus.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.7 inch Flexible AMOLED",
    },
    shortDescription: "Unique transparent budget phone with upgraded processor",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },

  // --- 12. Tecno ---
  {
    name: "Tecno Phantom V Fold",
    brand: "Tecno",
    type: "mobile",
    price: 88000,
    images: ["https://i.ibb.co.com/r2wJbTHF/Tecno-Phantom-V-Fold.jpg"],
    specs: {
      ram: "12GB",
      storage: "512GB",
      display: "7.85 inch Foldable LTPO AMOLED",
    },
    shortDescription: "Most affordable full-sized foldable smartphone",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Tecno Camon 30 Pro 5G",
    brand: "Tecno",
    type: "mobile",
    price: 36000,
    images: ["https://i.ibb.co.com/JF8KpffK/Tecno-Camon-30-Pro-5-G.jpg"],
    specs: { ram: "12GB", storage: "512GB", display: "6.78 inch AMOLED 144Hz" },
    shortDescription: "Camera focused mobile with Sony IMX890 sensor",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Tecno Megabook T1",
    brand: "Tecno",
    type: "laptop",
    price: 52000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      display: "15.6 inch FHD Display",
    },
    shortDescription: "Ultra-slim metallic body laptop with big battery",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Tecno Megabook S1",
    brand: "Tecno",
    type: "laptop",
    price: 115000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: {
      ram: "16GB",
      storage: "1TB SSD",
      display: "15.6 inch 3.2K 120Hz Display",
    },
    shortDescription: "Premium ultra-light flagship laptop",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },

  // --- 13. ZTE / Nubia ---
  {
    name: "Nubia RedMagic 9 Pro",
    brand: "ZTE / Nubia",
    type: "mobile",
    price: 95000,
    images: ["https://i.ibb.co.com/99DX8H4D/Nubia-Red-Magic-9-Pro.jpg"],
    specs: { ram: "16GB", storage: "512GB", display: "6.85 inch AMOLED 120Hz" },
    shortDescription: "Extreme gaming phone with built-in cooling fan",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Nubia Z60 Ultra",
    brand: "ZTE / Nubia",
    type: "mobile",
    price: 82000,
    images: ["https://i.ibb.co.com/B1h7GhD/Nubia-Z60-Ultra.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.8 inch AMOLED Under-Display Camera",
    },
    shortDescription: "Full-screen flagship phone with 35mm primary lens",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Nubia Pad 3D",
    brand: "ZTE / Nubia",
    type: "tablet",
    price: 125000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "8GB", storage: "256GB", display: "12.4 inch 3D AI IPS LCD" },
    shortDescription: "Glasses-free 3D tablet with AI eye-tracking",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "RedMagic Nova Gaming Tablet",
    brand: "ZTE / Nubia",
    type: "tablet",
    price: 68000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "12GB", storage: "256GB", display: "10.9 inch 2.8K 144Hz" },
    shortDescription: "Compact hardcore gaming tablet with active fan cooling",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },

  // --- 14. Vertu ---
  {
    name: "Vertu Metavertu II",
    brand: "Vertu",
    type: "mobile",
    price: 450000,
    images: ["https://i.ibb.co.com/C3FcsmFF/Vertu-Metavertu-II.webp"],
    specs: { ram: "12GB", storage: "512GB", display: "6.67 inch AMOLED 120Hz" },
    shortDescription: "Luxury Web3 AI phone wrapped in exotic leather",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Vertu Signature V",
    brand: "Vertu",
    type: "mobile",
    price: 980000,
    images: ["https://i.ibb.co.com/wF6rPmd1/Vertu-Signature-V.gif"],
    specs: {
      ram: "4GB",
      storage: "32GB",
      display: "2.0 inch Sapphire Crystal Display",
    },
    shortDescription:
      "Handcrafted luxury feature phone made with precious metals",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2022,
    createdAt: new Date(),
  },

  // --- 15. Realme ---
  {
    name: "Realme GT 6",
    brand: "Realme",
    type: "mobile",
    price: 54000,
    images: ["https://i.ibb.co.com/YFhddXtr/Realme-GT-6.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.78 inch 6000nit Ultra Bright AMOLED",
    },
    shortDescription: "Flagship killer phone with ultra-bright display",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Realme 12 Pro+ 5G",
    brand: "Realme",
    type: "mobile",
    price: 41000,
    images: ["https://i.ibb.co.com/cSLv6TGk/Realme-12-Pro-5-G.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.7 inch Curved OLED 120Hz",
    },
    shortDescription: "Luxury watch design phone with periscope portrait lens",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Realme Pad 2",
    brand: "Realme",
    type: "tablet",
    price: 24000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "6GB", storage: "128GB", display: "11.5 inch 2K 120Hz LCD" },
    shortDescription: "Smooth high-refresh display tablet for multimedia",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
  {
    name: "Realme Pad Mini",
    brand: "Realme",
    type: "tablet",
    price: 15500,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "4GB", storage: "64GB", display: "8.7 inch LCD" },
    shortDescription: "Compact and light pocket-sized tablet",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2022,
    createdAt: new Date(),
  },

  // --- 16. Honor ---
  {
    name: "Honor Magic V3",
    brand: "Honor",
    type: "mobile",
    price: 185000,
    images: ["https://i.ibb.co.com/zWMdc8VR/Honor-Magic-V3.jpg"],
    specs: {
      ram: "16GB",
      storage: "512GB",
      display: "7.92 inch Foldable OLED",
    },
    shortDescription: "World's thinnest inward foldable smartphone",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Honor 200 Pro",
    brand: "Honor",
    type: "mobile",
    price: 62000,
    images: ["https://i.ibb.co.com/FR78bwh/Honor-200-Pro.webp"],
    specs: { ram: "12GB", storage: "512GB", display: "6.78 inch Curved OLED" },
    shortDescription: "Studio Harcourt portrait photography phone",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Honor MagicBook Pro 16",
    brand: "Honor",
    type: "laptop",
    price: 165000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: {
      ram: "32GB",
      storage: "1TB SSD",
      display: "16.0 inch 3K 165Hz Spatial Audio",
    },
    shortDescription: "AI-powered high-performance laptop with discrete GPU",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "Honor MagicBook X16",
    brand: "Honor",
    type: "laptop",
    price: 65000,
    images: ["https://i.ibb.co.com/35CGc10V/banner-04.jpg"],
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      display: "16.0 inch FHD Eye Comfort",
    },
    shortDescription: "Sleek metallic laptop with long battery life",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },

  // --- 17. OnePlus ---
  {
    name: "OnePlus 12",
    brand: "OnePlus",
    type: "mobile",
    price: 92000,
    images: ["https://i.ibb.co.com/rKfStv1Z/One-Plus-12.jpg"],
    specs: {
      ram: "16GB",
      storage: "512GB",
      display: "6.82 inch LTPO AMOLED 120Hz",
    },
    shortDescription: "Smooth and powerful flagship with Hasselblad cameras",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "OnePlus Nord 4 5G",
    brand: "OnePlus",
    type: "mobile",
    price: 42000,
    images: ["https://i.ibb.co.com/QFgcx11N/One-Plus-Nord-4-5-G.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "6.74 inch Ultra-Bright AMOLED",
    },
    shortDescription: "All-metal unibody mid-range smartphone",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "OnePlus Pad 2",
    brand: "OnePlus",
    type: "tablet",
    price: 58000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: {
      ram: "12GB",
      storage: "256GB",
      display: "12.1 inch 3K 144Hz ReadFit Display",
    },
    shortDescription: "Powerful productivity tablet with Snapdragon 8 Gen 3",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2024,
    createdAt: new Date(),
  },
  {
    name: "OnePlus Pad Go",
    brand: "OnePlus",
    type: "tablet",
    price: 28000,
    images: ["https://i.ibb.co.com/6JVvcf82/banner-03.jpg"],
    specs: { ram: "8GB", storage: "128GB", display: "11.35 inch 2.4K Display" },
    shortDescription:
      "Budget entertainment tablet with Dolby Atmos Quad Speakers",
    fullDescription: "Detailed description will be added here",
    releaseYear: 2023,
    createdAt: new Date(),
  },
];

const seed = async () => {
  try {
    const db = await connectDB();

    // Purge existing data to avoid duplication
    await db.collection("products").deleteMany({});
    console.log("Old product data cleared.");

    // Insert new seed data
    await db.collection("products").insertMany(sampleProducts);
    console.log(
      `Successfully inserted ${sampleProducts.length} products into the database!`,
    );

    process.exit(0);
  } catch (err) {
    console.error("Error during database seeding:", err);
    process.exit(1);
  }
};

seed();